# Generated by Django 5.2.4 on 2025-12-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('round_video', 'Round Video')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='waveform',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
